### ISSUE TITLE
Colab notebooks: Cannot interpret 'DType(AnyFloat)' as a data type

### ISSUE THREAD

**Issue by idaho777** [google-research/visu3d#68] opened 2022-10-16 04:01 UTC
When I run the intro colab notebook I am unable to run the first cell initializing a Ray.

Running:
`ray = v3d.Ray(pos=[0, 0, 0], dir=[1, -1, 1])`

Error:
"Invalid shape annotation FloatArray[*shape 3].Cannot interpret 'DType(AnyFloat)' as a data type".

**Comment by Conchylicultor** [comment] 2022-10-17 09:22
Thank you for reporting. I believe the issue is a version missmatch between `etils` and `visu3d` (visu3d/dataclass_array expect an older version of etils). I'll trigger a new release of visu3d today which should fix the issue

**Comment by Conchylicultor** [comment] 2022-10-17 14:09
`visu3d` 1.3.0 was released which should fix the issue.

It seems the colab still has some issue in some cells with `ecolab.auto_plot_images()` which expect a more recent version of `mediapy`. 

```
TypeError: show_images() got an unexpected keyword argument 'return_html'
```

But this is a different issue. Fo now it can be fixed by replacing:

```python
rgb = ex['color_image']
rgb
```

By:

```python
rgb = ex['color_image']
media.show_images(rgb)
```

Will contact the mediapy team to see if they can trigger a release.

**Closed by Conchylicultor** 2022-10-17 14:09 UTC

**Comment by idaho777** [comment] 2022-10-17 14:54
This solved my issues.  Thank you!
